project:
  type: website
  output-dir: docs

website:
  title: "Alexandra Stauffer - MUSA 5080 Portfolio"
  description: "empty" 
  navbar:
    left:
    - href: index.qmd
      text: Home
    - text: Weekly Notes
      menu:
        - href: weekly-notes/week-01-notes.qmd
          text: Week 1
        - href: weekly-notes/week-02-notes.qmd
          text: Week 2
        - href: weekly-notes/week-03-notes.qmd
          text: Week 3
        - href: weekly-notes/week-04-notes.qmd
          text: Week 4
    - text: Labs
      menu:
        - href: labs/lab0/lab0_template.qmd
          text: "Lab 0: dplyr Basics"
        - href: labs/lab1/assignment1_template.qmd
          text: "Lab 1: Census Data Exploration"

format:
  html:
    theme: superhero
    toc: true
    code-fold: true

execute:
  freeze: auto
