project:
  type: website
  output-dir: docs

website:
  title: "Alex Stauffer - MUSA 5080 Portfolio"
  description: "empty" 
  navbar:
  title: "Portfolio"
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: "About"
      - text: "Weekly Notes"
        menu:
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2"

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
